"""Hermes Agent ``MemoryProvider`` backed by the shared Memplex runtime.

Hermes imports this module through a tiny profile-local bootstrap generated by
``memplex agent install --agent hermes``.  Turn writes stay non-blocking and
ordered, while compression/session/shutdown hooks synchronously drain accepted
work before the host can discard context or exit.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import queue
import re
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from agent.memory_provider import MemoryProvider

from memplex.adapters.agent_runtime import AgentMemoryRuntime
from memplex.config import load_config
from memplex.service import MemplexService

logger = logging.getLogger(__name__)

_PRIVATE_TAG_RE = re.compile(r"<private>.*?</private>", re.DOTALL | re.IGNORECASE)
_RECALLED_BLOCK_RE = re.compile(
    r"<relevant-memories>.*?</relevant-memories>",
    re.DOTALL | re.IGNORECASE,
)
_STOP = object()


@dataclass
class _WorkItem:
    kind: str
    session_id: str
    user: str = ""
    assistant: str = ""
    query: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    turn_key: str = ""
    done: threading.Event = field(default_factory=threading.Event)
    error: Exception | None = None


def _clean_text(value: Any) -> str:
    text = value.strip() if isinstance(value, str) else ""
    text = _PRIVATE_TAG_RE.sub("", text)
    return _RECALLED_BLOCK_RE.sub("", text).strip()


def _clean_value(value: Any) -> Any:
    if isinstance(value, str):
        return _clean_text(value)
    if isinstance(value, list):
        return [_clean_value(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _clean_value(item) for key, item in value.items()}
    return value


def _content_text(content: Any) -> str:
    if isinstance(content, str):
        return _clean_text(content)
    if not isinstance(content, list):
        return ""
    parts: list[str] = []
    for item in content:
        if isinstance(item, str):
            parts.append(item)
            continue
        if not isinstance(item, dict):
            continue
        item_type = str(item.get("type") or "").strip()
        if item_type and item_type not in {"text", "input_text", "output_text"}:
            continue
        candidate = item.get("text") or item.get("content")
        if isinstance(candidate, str):
            parts.append(candidate)
    return _clean_text("\n".join(parts))


def _last_completed_turn(messages: Any) -> tuple[str, str]:
    if not isinstance(messages, list):
        return "", ""
    pending_user = ""
    completed = ("", "")
    for message in messages:
        if not isinstance(message, dict):
            continue
        role = str(message.get("role") or "").strip().lower()
        content = _content_text(message.get("content"))
        if not content:
            continue
        if role == "user":
            pending_user = content
        elif role == "assistant" and pending_user:
            completed = pending_user, content
    return completed


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Memplex Hermes config load failed for %s: %s", path, exc)
        return {}
    return value if isinstance(value, dict) else {}


def _validated_managed_identity(identity: dict[str, Any]) -> dict[str, str]:
    managed = identity.get("managed")
    if not isinstance(managed, dict) or not (
        managed.get("by") == "memplex" or managed.get("installer") == "memplex"
    ):
        return {}
    user_id = str(identity.get("user_id") or "").strip()
    project_path = str(identity.get("project_path") or "").strip()
    if not user_id or not project_path:
        return {}
    return {"user_id": user_id, "project_path": project_path}


def _write_json_atomic(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o600
    temporary = path.with_name(f".{path.name}.memplex.tmp")
    temporary.write_text(
        json.dumps(value, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.chmod(mode)
    temporary.replace(path)


class MemplexMemoryProvider(MemoryProvider):
    """Hermes provider with ordered async writes and durable finalization."""

    def __init__(
        self,
        identity: Optional[Dict[str, Any]] = None,
        *,
        service_factory: Optional[Callable[[], MemplexService]] = None,
        runtime_factory: Optional[Callable[..., AgentMemoryRuntime]] = None,
    ) -> None:
        self._identity = dict(identity or {})
        self._service_factory = service_factory or self._create_service
        self._runtime_factory = runtime_factory or AgentMemoryRuntime
        self._service: MemplexService | None = None
        self._owns_service = False
        self._runtimes: dict[str, AgentMemoryRuntime] = {}
        self._runtime: AgentMemoryRuntime | None = None
        self._runtime_lock = threading.RLock()
        self._work_queue: queue.Queue[_WorkItem | object] = queue.Queue()
        self._worker: threading.Thread | None = None
        self._worker_lock = threading.Lock()
        self._pending_items: dict[int, _WorkItem] = {}
        self._pending_lock = threading.Lock()
        self._capture_lock = threading.Lock()
        self._queued_turns: set[str] = set()
        self._captured_turns: set[str] = set()
        self._captured_order: deque[str] = deque()
        self._closed = False
        self._initialized = False
        self._session_id = "default"
        self._hermes_home = str(Path.home() / ".hermes")
        self._config: dict[str, Any] = {}
        self._platform = "cli"
        self._agent_context = "primary"
        self._agent_identity = ""
        self._agent_workspace = ""
        self._parent_session_id = ""
        self._platform_user_id = ""
        self._platform_user_id_alt = ""

    @property
    def name(self) -> str:
        return "memplex"

    def is_available(self) -> bool:
        """Availability is local-only; never perform network I/O here."""

        try:
            import memplex  # noqa: F401

            return True
        except Exception:
            return False

    def initialize(self, session_id: str, **kwargs: Any) -> None:
        if self._initialized and not self._closed:
            self.shutdown()
        self._closed = False
        self._session_id = str(session_id or "default")
        self._hermes_home = str(
            Path(kwargs.get("hermes_home") or Path.home() / ".hermes")
            .expanduser()
            .resolve(strict=False)
        )
        self._platform = str(kwargs.get("platform") or "cli")
        self._agent_context = str(kwargs.get("agent_context") or "primary")
        self._agent_identity = str(kwargs.get("agent_identity") or "")
        self._agent_workspace = str(kwargs.get("agent_workspace") or "")
        self._parent_session_id = str(kwargs.get("parent_session_id") or "")
        self._platform_user_id = str(kwargs.get("user_id") or "")
        self._platform_user_id_alt = str(kwargs.get("user_id_alt") or "")
        config = {
            "user_id": os.environ.get("MEMPLEX_USER_ID") or self._identity.get("user_id"),
            "project_path": os.environ.get("MEMPLEX_PROJECT_ROOT")
            or self._identity.get("project_path")
            or os.getcwd(),
            "prefetch": True,
            "top_k": 5,
            "token_budget": 1500,
            "visibility": "workspace",
            "flush_timeout_seconds": 10.0,
        }
        config.update(
            {
                key: value
                for key, value in _read_json(Path(self._hermes_home) / "memplex.json").items()
                if value not in (None, "")
            }
        )
        dynamic_project = (
            kwargs.get("workspace_dir")
            or kwargs.get("project_path")
            or kwargs.get("cwd")
            or kwargs.get("agent_workspace_path")
        )
        if dynamic_project:
            config["project_path"] = dynamic_project
        managed_identity = _validated_managed_identity(self._identity)
        if managed_identity:
            config.update(managed_identity)
        user_id = str(config.get("user_id") or "").strip()
        if not user_id or user_id == "default":
            raise ValueError("Hermes Memplex provider requires a non-default user_id")
        config["user_id"] = user_id
        config["project_path"] = str(
            Path(config.get("project_path") or os.getcwd()).expanduser().resolve(strict=False)
        )
        self._config = config
        self._runtimes.clear()
        self._runtime = None
        self._reset_capture_dedupe()
        self._initialized = True
        self._ensure_worker()

    def get_config_schema(self) -> List[Dict[str, Any]]:
        return [
            {
                "key": "user_id",
                "description": "Stable Memplex user id shared with other agent hosts",
                "required": True,
                "default": self._identity.get("user_id") or "",
            },
            {
                "key": "project_path",
                "description": "Canonical workspace path used for shared memory scope",
                "required": True,
                "default": self._identity.get("project_path") or os.getcwd(),
            },
        ]

    def save_config(self, values: Dict[str, Any], hermes_home: str) -> None:
        path = Path(hermes_home).expanduser().resolve(strict=False) / "memplex.json"
        existing = _read_json(path)
        managed = existing.get("managed") or self._identity.get("managed")
        existing.update({key: value for key, value in values.items() if value not in (None, "")})
        existing.setdefault("name", "memplex")
        existing.setdefault("provider", "memplex")
        if managed:
            existing["managed"] = managed
        _write_json_atomic(path, existing)

    def system_prompt_block(self) -> str:
        return (
            "Memplex shared memory is active. Relevant workspace memories are "
            "recalled before turns; use memplex_search or memplex_conclude when explicit "
            "memory access is useful."
        )

    def prefetch(self, query: str, *, session_id: str = "") -> str:
        cleaned = _clean_text(query)
        if not cleaned:
            return ""
        self._select_session(session_id)
        return self._ensure_runtime().before_prompt(cleaned).context

    def queue_prefetch(self, query: str, *, session_id: str = "") -> None:
        cleaned = _clean_text(query)
        if not cleaned or not bool(self._config.get("prefetch", True)):
            return
        selected = str(session_id or self._session_id or "default")
        self._enqueue(_WorkItem(kind="prefetch", session_id=selected, query=cleaned))

    def sync_turn(
        self,
        user_content: str,
        assistant_content: str,
        *,
        session_id: str = "",
        messages: Optional[List[Dict[str, Any]]] = None,
    ) -> None:
        if not self._writes_enabled():
            return
        user = _clean_text(user_content)
        assistant = _clean_text(assistant_content)
        if not user and not assistant:
            return
        selected = str(session_id or self._session_id or "default")
        if selected != self._session_id:
            self._session_id = selected
            self._runtime = self._runtimes.get(selected)
        metadata = self._metadata(
            "sync_turn",
            hermes_messages=_clean_value(messages or []),
        )
        self._queue_capture(user, assistant, selected, metadata)

    def on_pre_compress(self, messages: List[Dict[str, Any]]) -> str:
        self._flush_or_warn("pre-compress")
        captured = self._capture_last_turn(messages, "on_pre_compress")
        return "Memplex preserved the latest completed turn." if captured else ""

    def on_session_end(self, messages: List[Dict[str, Any]]) -> None:
        self._flush_or_warn("session-end")
        self._capture_last_turn(messages, "on_session_end")
        self._flush_or_warn("session-end-final")

    def on_session_switch(
        self,
        new_session_id: str,
        *,
        parent_session_id: str = "",
        reset: bool = False,
        rewound: bool = False,
        **kwargs: Any,
    ) -> None:
        self._flush_or_warn("session-switch")
        selected = str(new_session_id or "default")
        if rewound:
            with self._runtime_lock:
                self._runtimes.pop(selected, None)
                if self._session_id == selected:
                    self._runtime = None
        self._session_id = selected
        self._parent_session_id = str(parent_session_id or "")
        if reset:
            self._reset_capture_dedupe()
        self._agent_context = str(kwargs.get("agent_context") or self._agent_context)

    def on_memory_write(
        self,
        action: str,
        target: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        cleaned = _clean_text(content)
        if action not in {"add", "replace"} or not cleaned or not self._writes_enabled():
            return
        details = self._metadata(
            "on_memory_write",
            hermes_memory_action=action,
            hermes_memory_target=target,
            hermes_memory_metadata=_clean_value(metadata or {}),
        )
        self._queue_capture(
            cleaned,
            f"Mirrored from Hermes built-in {target} memory.",
            self._session_id,
            details,
        )

    def on_delegation(
        self,
        task: str,
        result: str,
        *,
        child_session_id: str = "",
        **kwargs: Any,
    ) -> None:
        if not self._writes_enabled():
            return
        cleaned_task = _clean_text(task)
        cleaned_result = _clean_text(result)
        if not cleaned_task and not cleaned_result:
            return
        self._queue_capture(
            cleaned_task,
            cleaned_result,
            self._session_id,
            self._metadata(
                "on_delegation",
                hermes_child_session_id=child_session_id,
                hermes_delegation_context=_clean_value(kwargs),
            ),
        )

    def get_tool_schemas(self) -> List[Dict[str, Any]]:
        return [
            {
                "name": "memplex_search",
                "description": "Search shared local Memplex memories for this user/workspace.",
                "parameters": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "query": {"type": "string", "minLength": 1},
                    },
                    "required": ["query"],
                },
            },
            {
                "name": "memplex_conclude",
                "description": "Store one durable conclusion in shared Memplex memory.",
                "parameters": {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "content": {"type": "string", "minLength": 1},
                        "visibility": {
                            "type": "string",
                            "enum": ["session", "workspace", "user"],
                            "default": "workspace",
                        },
                    },
                    "required": ["content"],
                },
            },
        ]

    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs: Any) -> str:
        if tool_name == "memplex_search":
            runtime = self._ensure_runtime()
            query = _clean_text(args.get("query"))
            if not query:
                return json.dumps({"context": "", "total": 0}, ensure_ascii=False)
            recalled = runtime.before_prompt(query)
            return json.dumps(
                {"context": recalled.context, "total": recalled.total},
                ensure_ascii=False,
            )
        if tool_name == "memplex_conclude":
            if not self._writes_enabled():
                return json.dumps(
                    {"status": "ignored", "reason": "non_primary_context"},
                    ensure_ascii=False,
                )
            content = _clean_text(args.get("content"))
            if not content:
                return json.dumps({"status": "ignored", "reason": "empty_content"})
            runtime = self._ensure_runtime()
            visibility = str(
                args.get("visibility") or self._config.get("visibility") or "workspace"
            )
            runtime.capture_turn(
                content,
                "Stored explicitly by Hermes memplex_conclude.",
                metadata={
                    **self._metadata("memplex_conclude"),
                    "tool_name": "memplex_conclude",
                    "memplex_visibility": visibility,
                },
            )
            return json.dumps({"status": "stored"}, ensure_ascii=False)
        raise NotImplementedError(f"Unknown Memplex tool: {tool_name}")

    def backup_paths(self) -> List[str]:
        path = self._config.get("storage_path") or os.environ.get("MEMPLEX_STORAGE_PATH")
        return [str(Path(path).expanduser().resolve(strict=False))] if path else []

    def shutdown(self) -> None:
        if self._closed:
            return
        self._flush_or_warn("shutdown")
        worker = self._worker
        if worker and worker.is_alive():
            self._work_queue.put(_STOP)
            worker.join(timeout=self._flush_timeout())
            if worker.is_alive():
                logger.warning("Memplex Hermes worker did not stop before timeout")
        self._worker = None
        if self._service is not None and self._owns_service:
            try:
                self._service.stop()
            except Exception as exc:
                logger.warning("Memplex service shutdown failed: %s", exc)
        self._service = None
        self._owns_service = False
        self._runtimes.clear()
        self._runtime = None
        self._closed = True

    def _create_service(self) -> MemplexService:
        service = MemplexService(config=load_config())
        service.start()
        return service

    def _ensure_service(self) -> MemplexService:
        if self._service is None:
            self._service = self._service_factory()
            self._owns_service = True
        return self._service

    def _ensure_runtime(self) -> AgentMemoryRuntime:
        return self._runtime_for_session(self._session_id)

    def _runtime_for_session(self, session_id: str) -> AgentMemoryRuntime:
        selected = str(session_id or "default")
        with self._runtime_lock:
            existing = self._runtimes.get(selected)
            if existing is None and self._runtime is not None and selected == self._session_id:
                existing = self._runtime
            if existing is None:
                existing = self._runtime_factory(
                    service=self._ensure_service(),
                    agent="hermes",
                    user_id=self._config["user_id"],
                    session_id=selected,
                    project_path=self._config["project_path"],
                    top_k=int(self._config.get("top_k") or 5),
                    token_budget=int(self._config.get("token_budget") or 1500),
                    prefetch=bool(self._config.get("prefetch", True)),
                )
                self._runtimes[selected] = existing
            if selected == self._session_id:
                self._runtime = existing
            return existing

    def _select_session(self, session_id: str) -> None:
        selected = str(session_id or self._session_id or "default")
        if selected == self._session_id:
            return
        self._flush_or_warn("session-rebind")
        self._session_id = selected
        self._runtime = self._runtimes.get(selected)

    def _ensure_worker(self) -> None:
        with self._worker_lock:
            if self._worker and self._worker.is_alive():
                return
            self._worker = threading.Thread(
                target=self._worker_loop,
                name="memplex-hermes-memory",
                daemon=True,
            )
            self._worker.start()

    def _enqueue(self, item: _WorkItem) -> None:
        if self._closed:
            logger.warning("Memplex Hermes work ignored after shutdown")
            return
        self._ensure_worker()
        identifier = id(item)
        with self._pending_lock:
            self._pending_items[identifier] = item
        self._work_queue.put(item)

    def _queue_capture(
        self,
        user: str,
        assistant: str,
        session_id: str,
        metadata: dict[str, Any],
    ) -> bool:
        turn_key = self._turn_key(user, assistant, session_id)
        with self._capture_lock:
            if turn_key in self._queued_turns or turn_key in self._captured_turns:
                return False
            self._queued_turns.add(turn_key)
        self._enqueue(
            _WorkItem(
                kind="capture",
                session_id=session_id,
                user=user,
                assistant=assistant,
                metadata=metadata,
                turn_key=turn_key,
            )
        )
        return True

    def _worker_loop(self) -> None:
        while True:
            item = self._work_queue.get()
            if item is _STOP:
                self._work_queue.task_done()
                return
            assert isinstance(item, _WorkItem)
            try:
                if item.kind == "capture":
                    runtime = self._runtime_for_session(item.session_id)
                    runtime.after_response(
                        user_message=item.user,
                        assistant_message=item.assistant,
                        metadata=item.metadata,
                    )
                    self._mark_captured(item.turn_key)
                elif item.kind == "prefetch":
                    self._runtime_for_session(item.session_id).prefetch(item.query)
            except Exception as exc:
                item.error = exc
                if item.turn_key:
                    with self._capture_lock:
                        self._queued_turns.discard(item.turn_key)
                logger.warning("Memplex Hermes %s failed: %s", item.kind, exc)
            finally:
                item.done.set()
                identifier = id(item)
                with self._pending_lock:
                    self._pending_items.pop(identifier, None)
                self._work_queue.task_done()

    def _flush(self, timeout: float | None = None) -> bool:
        deadline = time.monotonic() + (self._flush_timeout() if timeout is None else timeout)
        while True:
            with self._pending_lock:
                pending = list(self._pending_items.values())
            if not pending:
                return True
            for item in pending:
                remaining = deadline - time.monotonic()
                if remaining <= 0 or not item.done.wait(remaining):
                    return False

    def _flush_or_warn(self, reason: str) -> None:
        if not self._flush():
            logger.warning("Memplex Hermes %s flush timed out", reason)

    def _capture_last_turn(self, messages: Any, hook: str) -> bool:
        if not self._writes_enabled():
            return False
        user, assistant = _last_completed_turn(messages)
        if not user and not assistant:
            return False
        turn_key = self._turn_key(user, assistant, self._session_id)
        with self._capture_lock:
            if turn_key in self._queued_turns or turn_key in self._captured_turns:
                return False
            self._queued_turns.add(turn_key)
        try:
            self._runtime_for_session(self._session_id).after_response(
                user_message=user,
                assistant_message=assistant,
                metadata=self._metadata(hook, hermes_messages=_clean_value(messages)),
            )
            self._mark_captured(turn_key)
            return True
        except Exception as exc:
            with self._capture_lock:
                self._queued_turns.discard(turn_key)
            logger.warning("Memplex Hermes %s capture failed: %s", hook, exc)
            return False

    def _mark_captured(self, turn_key: str) -> None:
        if not turn_key:
            return
        with self._capture_lock:
            self._queued_turns.discard(turn_key)
            if turn_key in self._captured_turns:
                return
            self._captured_turns.add(turn_key)
            self._captured_order.append(turn_key)
            while len(self._captured_order) > 512:
                expired = self._captured_order.popleft()
                self._captured_turns.discard(expired)

    def _reset_capture_dedupe(self) -> None:
        with self._capture_lock:
            self._queued_turns.clear()
            self._captured_turns.clear()
            self._captured_order.clear()

    @staticmethod
    def _turn_key(user: str, assistant: str, session_id: str) -> str:
        raw = json.dumps(
            [str(session_id or "default"), user, assistant],
            ensure_ascii=False,
            separators=(",", ":"),
        )
        return hashlib.sha256(raw.encode()).hexdigest()

    def _metadata(self, hook: str, **extra: Any) -> dict[str, Any]:
        return {
            "hook_event_name": hook,
            "hermes_platform": self._platform,
            "hermes_agent_context": self._agent_context,
            "hermes_agent_identity": self._agent_identity,
            "hermes_agent_workspace": self._agent_workspace,
            "hermes_parent_session_id": self._parent_session_id,
            "hermes_platform_user_id": self._platform_user_id,
            "hermes_platform_user_id_alt": self._platform_user_id_alt,
            "memplex_visibility": str(self._config.get("visibility") or "workspace"),
            **extra,
        }

    def _writes_enabled(self) -> bool:
        return self._agent_context in {"", "primary"}

    def _flush_timeout(self) -> float:
        try:
            return max(0.1, float(self._config.get("flush_timeout_seconds") or 10.0))
        except (TypeError, ValueError):
            return 10.0


def register(ctx: Any, identity: Optional[Dict[str, Any]] = None) -> None:
    """Register the provider through Hermes' official plugin context."""

    ctx.register_memory_provider(MemplexMemoryProvider(identity=identity))
